title = "ronan.design"
base_url = "https://ronandotdesign-lc7ilta6.fermyon.app"
about = "Ronan Flynn-Curran is a UX designer and developer who works to make technical tools accessible and friendly to all."
# theme = "ronan"
# base_url = "http://localhost:3000"
# index_site_pages = ["home"]

[extra]
copyright = "Ronan Flynn-Curran"
github = "https://github.com/flynnduism/ronan.design"